### ISSUE TITLE
4.5 Alternativas y competencia

### ISSUE THREAD

**Issue by jjosee96** [cristian3457/C_Almacen_Tocumich#6]
En esta sección se menciona que el cliente nunca se había interesado por un sistema para automatizar el proceso de ventas o inventario y por lo tanto no se tiene competencia con ningún otro sistema, yo pienso que es todo lo contrario puesto que ahora el cliente esta interesado en un sistema, en caso de que esta propuesta no satisfaga sus necesidades, el cliente buscara otras propuestas o un sistema genérico en el mercado, por lo tanto se debe de replantear esta sección.

**Comment by Ramoshtvs** [comment]
Esta bien la observación, pero el cliente no estaba interesado en un sistema para mejorar  el control de almacén en su negocio, hasta que llegamos nosotros y se lo ofrecimos ademas no creo que puede irse con la competencia ya que nosotros se lo estamos ofreciendo gratuito y el cliente no estaba interesado en adquirir un sistema hasta que nosotros lo convencimos.
